pyconpune/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import cauth.urls
import root.urls
import ticket.urls
import payments.urls
from django.conf import settings

urlpatterns = [
    url(settings.BASE_URL, include([
        url(r'^admin/', admin.site.urls),
        url(r'', include(cauth.urls)),
        url(r'', include(ticket.urls)),
        url(r'', include(payments.urls)),
        url(r'^jet/', include('jet.urls', 'jet')),
        url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
        url(r'^account/', include('account.urls')),
    ])),
        url(r'', include(root.urls))
]

root/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

import root.views

urlpatterns = [
    url(settings.BASE_URL, include([
        url(r'^$', root.views.homepage,
            name="homepage"),
        url(r'^coc/$', root.views.coc,
            name="coc"),
        url(r'^volunteer/$', root.views.volunteer,
            name="volunteer"),
        url(r'^be_volunteer/$', root.views.be_volunteer,
            name="be_volunteer"),
        url(r'^about/$', root.views.about,
            name="about"),
        url(r'^sponsors/$', root.views.sponsors,
            name="sponsors"),
        url(r'^travelling/$', root.views.travelling,
            name="travelling"),
        url(r'^schedule/$', root.views.schedule,
            name="schedule"),
        url(r'^speakers/$', root.views.speakers,
            name="speakers")
    ]))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ticket/urls.py
from django.conf.urls import url

import ticket.views

urlpatterns = [
    url(r"^register/$", ticket.views.TicketApplicationView.as_view(),
        name="ticket_register"),

    url(r"^acknowledge/^$", ticket.views.acknowledge,
        name="ticket_acknowledge"),
]

payments/models.py
from django.db import models
from django.utils.translation import ugettext as _

from root.models import Base

class Invoice(Base):
    """Model to store data for the Invoice created"""

    invoice_id = models.CharField(_("invoice_id"), max_length=255)
    receipt_number = models.CharField(_("receipt_number"), max_length=255)
    order_id = models.CharField(_("order_id"), max_length=255)
    status = models.CharField(_("status"), max_length=255)
    payment_id = models.CharField(_("invoice_id"), max_length=255, null=True)
    expire_by = models.CharField(_("expire_by"), max_length=255, null=True)
    issued_at = models.CharField(_("issued_at"), max_length=255)
    paid_at = models.CharField(_("paid_at"), max_length=255, null=True)
    amount = models.PositiveIntegerField(_("amount"), default=0)
    currency = models.CharField(_("currency"), max_length=255)
    short_url = models.CharField(_("short_url"), max_length=255)
    conference = models.PositiveIntegerField(_("conference"), default=0)
    user = models.PositiveIntegerField(_("user"), default=0)


class Payment(Base):
    """Model to store data for the Payment created"""

    payment_id = models.CharField(_("payment_id"), max_length=255)
    amount = models.PositiveIntegerField(_("amount"), default=0)
    currency = models.CharField(_("currency"), max_length=255, null=True)
    status = models.CharField(_("status"), max_length=255, null=True)
    order_id = models.CharField(_("order_id"), max_length=255, null=True)
    invoice_id = models.CharField(_("invoice_id"), max_length=255, null=True)
    international = models.BooleanField(_("international?"), default=False,
                                           db_index=True)
    amount_refunded = models.PositiveIntegerField(_("amount"), default=0)
    refund_status = models.CharField(_("refund_status"), max_length=255, null=True)
    email = models.CharField(_("email"), max_length=255, null=True)
    contact = models.CharField(_("contact"), max_length=15, null=True,
                               blank=True)
    fee = models.PositiveIntegerField(_("fee"), default=0)
    service_tax = models.PositiveIntegerField(_("service_tax"), default=0)
    created_at = models.CharField(_("created_at"), max_length=255, null=True)


class Order(Base):
    """Model to store data for the Order created"""

    order_id = models.CharField(_("order_id"), max_length=255)
    amount = models.PositiveIntegerField(_("amount"), default=0)
    currency = models.CharField(_("currency"), max_length=255, null=True)
    status = models.CharField(_("status"), max_length=255, null=True)
    created_at = models.CharField(_("created_at"), max_length=255, null=True)


class RazorpayKeys(Base):
    """ Model to store Razorpay Keys """

    api_key = models.CharField(_("api key"), max_length=255)
    api_secret = models.CharField(_("api secret"), max_length=255)

pyconpune/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

ticket/models.py
import uuid

from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import ugettext as _

from symposion.conference.models import Conference

from cauth.models import EventUser
from root.models import Base


class Ticket(Base):
    """ Model to store the different types of ticket. """

    title = models.CharField(_("name"), max_length=255)
    limits = models.PositiveIntegerField(_("limits"), default=0)
    price = models.PositiveIntegerField(_("price"), default=0, db_index=True)
    description = models.CharField(_("description"), max_length=255, null=True)
    image_base64_title = models.CharField(_("image title"), max_length=255,
                                          null=True, blank=True)
    image_base64_text = models.TextField(_("image url"), null=True, blank=True)
    conference = models.ForeignKey(Conference, verbose_name=_("conference"))
    is_limit_reached = models.BooleanField(_("limit reached?"), default=False,
                                           db_index=True)
    disabled = models.BooleanField(_("disabled?"), default=False, db_index=True)

    class Meta:
        verbose_name = _("ticket")
        verbose_name_plural = _("tickets")

    def __str__(self):
        return u"%s: %s" % (self.conference.title, self.title)


class AuxiliaryTicket(Base):
    """ Model for the auxiliary tickets, which the user can
    buy in addition to the main ticket"""
    title = models.CharField(_('name'), max_length=255)
    limits = models.PositiveIntegerField(_("limits"), default=0)
    price = models.PositiveIntegerField(_('price'), default=0)
    description = models.CharField(_("description"), max_length=255, null=True)
    image_base64_title = models.CharField(_("image title"), max_length=255,
                                          null=True, blank=True)
    image_base64_text = models.TextField(_("image url"), null=True, blank=True)
    conference = models.ForeignKey(Conference, verbose_name=_("conference"))
    is_limit_reached = models.BooleanField(_("limit reached?"), default=False,
                                           db_index=True)
    disabled = models.BooleanField(_("disabled?"), default=False, db_index=True)

class TicketAddons(Base):
    """ Model for the addons for the tickets, which needs to be bought along
    with the ticket. """
    title = models.CharField(_('name'), max_length=255)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    price = models.PositiveIntegerField(_('price'), default=0)


class CouponCode(Base):
    """ Model for storing the coupon code, which can be applied on both the
    Ticket & TicketAddons.
    """
    code = models.CharField(_('coupon'), max_length=20)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')


class UserTicket(Base):
    """ Model for maitaining the ticket entry for all the Users. """

    uuid = models.UUIDField(default=uuid.uuid4, editable=False)
    user = models.ForeignKey(EventUser, on_delete=models.CASCADE)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)

    invoice = models.CharField(_('invoice'), max_length=255, default=0)
    auxiliary_ticket_id = models.CommaSeparatedIntegerField(
        _('auxiliary ticket'),
        default=0,
        max_length=200
    )

    is_payment_done = models.BooleanField(
        _("payment done?"),
        default=False
    )

    class Meta:
        verbose_name = _("user ticket")
        verbose_name_plural = _("user tickets")
        ordering = ['-timestamp']

    def __str__(self):
        return u'%s:%s' % (self.user.username, self.ticket.title)

ticket/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext as _

import account.forms

from cauth.models import AGE_GROUP_CHOICES, OCCUPATION_CHOICES, TSHIRT_SIZE_CHOICES
from ticket.models import UserTicket


class TicketApplicationForm(forms.ModelForm):
    """ Ticket Application Form """

    class Meta:
        model = UserTicket
        fields = [
            "ticket",
            "auxiliary_ticket_id"
        ]


class UserRegistrationForm(account.forms.SignupForm):
    first_name = forms.CharField(
        label=_('First Name'),
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('First Name')
        },
    ))
    last_name = forms.CharField(
        label=_('Last Name'),
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Last Name')
        }),
    )
    contact = forms.CharField(
        label=_('Contact No.'),
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Contact')
        },
    ))
    location = forms.CharField(
        label=_('Location'),
        required=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Location')
        }),
    )
    age_group = forms.TypedChoiceField(
        label=_('Age Group'),
        required=True,
        choices=AGE_GROUP_CHOICES,
        widget=forms.Select(attrs={
            'class': 'form-control',
        }),
    )
    gender = forms.CharField(
        label=_('Gender'),
        required=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Gender')
        }),
    )
    tshirt_size = forms.TypedChoiceField(
        label=_('Tshirt Size'),
        required=True,
        choices=TSHIRT_SIZE_CHOICES,
        widget=forms.Select(attrs={
            'class': 'form-control',
        }),
    )
    occupation = forms.TypedChoiceField(
        label=_('Occupation'),
        required=True,
        choices=OCCUPATION_CHOICES,
        widget=forms.Select(attrs={
            'class': 'form-control',
            'placeholder': _('Occupation'),
        }),
    )
    company = forms.CharField(
        label=_('Company'),
        required=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Company')
        }),
    )
    job_title = forms.CharField(
        label=_('Job Title'),
        required=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Job Title'),
        }),
    )

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        del self.fields["username"]
        del self.fields["password"]
        del self.fields["password_confirm"]

        self.fields.keyOrder = [
            "email",
            "first_name",
            "last_name",
            "contact",
            "location",
            "age_group",
            "gender",
            "tshirt_size",
            "occupation",
            "company",
            "company_title",
            "website"
        ]
 
        self.fields['email'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Email')
        })
        self.fields['email'].required = True

        if AGE_GROUP_CHOICES[0][0] != '0':
            AGE_GROUP_CHOICES.insert(0, ('0', _('Please select an age group.')))
        self.fields['age_group'].choices = AGE_GROUP_CHOICES

        if OCCUPATION_CHOICES[0][0] != 'Z':
            OCCUPATION_CHOICES.insert(0, ('Z', _('Please select an occupation.')))
        self.fields['occupation'].choices = OCCUPATION_CHOICES

        if TSHIRT_SIZE_CHOICES[0][0] != 'XXX':
            TSHIRT_SIZE_CHOICES.insert(0, ('XXX', _('Please select a tshirt size.')))
        self.fields['tshirt_size'].choices = TSHIRT_SIZE_CHOICES

pyconpune/templates/ticket/application.html
{% extends "inner_site_base.html" %}

{% load staticfiles %}

{% block extraheader %}
    <link href='{% static "css/tickets/ticket.css" %}' rel="stylesheet">
{% endblock %}

{% block body %}
<!-- Ticket v0 Section -->
<section id="ticket" class="content-section text-center" style="background-color:white; width:100%;padding-bottom:5em">
  <div class="row container" style="margin:auto; text-align: left;">
    <div class="col-lg-12">
      <h2 class="no-text-transform">Tickets</h2>
      <div class="underline"></div>
      <div id="accordion" role="tablist" aria-multiselectable="true">
        <div class="card mb-3">
          <div class="card-header" role="tab" id="ticket-row-header-1">
            <h4 class="mb-0 no-margin">
              <a data-toggle="collapse" data-parent="#accordion" href="#ticket-row-1" aria-expanded="true" aria-controls="ticket-row-1">
                Select the ticket to buy?
              </a>
            </h4>
          </div>
          <div id="ticket-row-1" class="ticket-row collapse" role="tabpanel" aria-labelledby="ticket-row-heading-1">
            <div class="card-block">
              {% include "ticket/select_ticket.html" %}
              <div class="clear"></div>
            </div>
          </div>
        </div>

        <div class="card mb-3">
          <div class="card-header" role="tab" id="ticket-row-header-2">
            <h4 class="mb-0 no-margin">
              <a data-toggle="collapse" data-parent="#accordion" href="#ticket-row-2" aria-expanded="true" aria-controls="ticket-row-2">
                Few additional ones...
              </a>
            </h4>
          </div>

          <div id="ticket-row-2" class="ticket-row collapse" role="tabpanel" aria-labelledby="ticket-row-heading-2">
            <div class="card-block">
              {% include "ticket/select_auxillary_ticket.html" %}
              <div class="clear"></div>
            </div>
          </div>
        </div>

        <div class="card mb-3">
          <div class="card-header mb-10" role="tab" id="ticket-row-header-3">
            <h4 class="mb-0 no-margin">
              <a data-toggle="collapse" data-parent="#accordion" href="#ticket-row-3" aria-expanded="true" aria-controls="ticket-row-3">
                Please enter your details
              </a>
            </h4>
          </div>

          <div id="ticket-row-3" class="ticket-row collapse" role="tabpanel" aria-labelledby="ticket-row-heading-3">
            <div class="card-block col-lg-9">
              {% include "ticket/user_details.html" %}
              <div class="clear"></div>
            </div>
            <div class="card-block col-lg-3">
              {% include "ticket/order_detail.html" %}
              <div class="clear"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

{% block extrajs %}
<script type="text/javascript" src="{% static 'js/tickets/ticket.js' %}">   </script>
{% endblock %}

pyconpune/templates/ticket/detail.html
{% extends "site_base.html" %}

{% block content %}
This is ticket detail adding page
{% if form %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>
{% else %}
    No Form
{% endif %}
{% endblock %}

pyconpune/templates/ticket/order_detail.html
<div class="payment-breakup-row">
  <h4>Order Details</h4>
</div><hr>
<div class="payment-breakup-row">
  <div class="col-lg-8"><b>Items</b></div>
  <div class="col-lg-4"><b>Prices</b></div>
  <div class="clear"></div>
</div>
<div class="payment-breakup-row" id="conference-ticket">
  <div class="col-lg-8 item"></div>
  <div class="col-lg-4 price"></div>
  <div class="clear"></div>
</div>
<div class="payment-breakup-row" id="auxiliary-ticket">
  <div class="col-lg-8 item"></div>
  <div class="col-lg-4 price"></div>
  <div class="clear"></div>
</div>
<div class="payment-breakup-row" id="tshirt-ticket-1">
  <div class="col-lg-8 item"></div>
  <div class="col-lg-4 price"></div>
  <div class="clear"></div>
</div>
<div class="payment-breakup-row" id="tshirt-ticket-2">
  <div class="col-lg-8 item"></div>
  <div class="col-lg-4 price"></div>
  <div class="clear"></div>
</div>
<hr>
<div class="payment-breakup-row" id="total-without-tax">
  <div class="col-lg-8 item">Total before tax</div>
  <div class="col-lg-4 total-price">₹0</div>
  <div class="clear"></div>
</div>
<div class="payment-breakup-row" id="tax">
  <div class="col-lg-8 item">Tax(18%)</div>
  <div class="col-lg-4 tax-price">₹0</div>
  <div class="clear"></div>
</div>
<hr>
<div class="payment-breakup-row" id="total-with-tax">
  <b><div class="col-lg-8 item">Total after tax</div></b>
  <b><div class="col-lg-4 total-price">₹0</div></b>
  <div class="clear"></div>
</div>

pyconpune/templates/ticket/select_ticket.html
    {% for ticket in tickets %}
    <div id="ticket-row-1-{{ forloop.counter }}" class="p-ticket ticket col-xl-4 col-lg-4 col-md-12 mb-5 mb-xl-2 mb-lg-2">
        <div class="ticket-outer">
            <div class="ticket-inner text-center" style="padding: 2em">
                <figure>
                    <!-- {{ ticket.image_base64_title }} icon by Icons8 -->
                    <img class="icon icons8-{{ ticket.image_base64_title }}" width="100" height="100" src="{{ ticket.image_base64_text }}">
                </figure>
                <h4 class="no-text-transform ticket-divider ticket-title font-w-700">{{ ticket.title }}</h4>
                <h1 class="no-text-transform ticket-price font-w-700">₹{{ ticket.price }}</h1>
                <div class="ticket-description ticket-divider">
                    <span>{{ ticket.description }}</span>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

pyconpune/templates/ticket/thanks.html
{% extends "inner_site_base.html" %}

{% block body %}
<div class="third-fold">
  <div class="fold-1">
    <div class="white-fold" style="color:black;">
      <div class="responsive-container">
        <h2 class='f-c no-text-transform'>Thanks for buying ticket</h2>
      </div>
    </div>
  </div>
</div><!-- third-fold -->
{% endblock %}

pyconpune/templates/ticket/user_details.html
                <div id="ticket-row-3" class="ticket-row">
                  <form id="ticket-register-form" class="form-horizontal" action="{% url 'ticket_register' %}" method="POST">{% csrf_token %}
                      {{ user_form.non_field_errors }}
                      <div class="form-group">
                          <label class="col-sm-2 control-label required" for="id_first_name">{{ user_form.first_name.label_tag }}</label>
                          <div class="col-sm-6">
                              {{ user_form.first_name }}
                          </div>
                          <div class="col-sm-4">
                              {{ user_form.first_name.errors }}
                          </div>
                      </div>
                      <div class="form-group">
                          <label class="col-sm-2 control-label required" for="id_last_name">{{ user_form.last_name.label_tag }}</label>
                          <div class="col-sm-6">
                              {{ user_form.last_name }}
                          </div>
                          <div class="col-sm-4">
                              {{ user_form.last_name.errors }}
                          </div>
                      </div>
                      <div class="form-group">
                          <label class="col-sm-2 control-label required" for="id_email">{{ user_form.email.label_tag }}</label>
                          <div class="col-sm-6">
                              {{ user_form.email }}
                          </div>
                          <div class="col-sm-4">
                              {{ user_form.email.errors }}
                          </div>
                      </div>
                      <div class="form-group">
                          <label class="col-sm-2 control-label required" for="id_contact">{{ user_form.contact.label_tag }}</label>
                          <div class="col-sm-6">
                              {{ user_form.contact }}
                          </div>
                          <div class="col-sm-4">
                              {{ user_form.contact.errors }}
                          </div>
                      </div>
                      <div class="form-group">
                          <label class="col-sm-2 control-label" for="id_location">{{ user_form.location.label_tag }}</label>
                          <div class="col-sm-6">
                              {{ user_form.location }}
                          </div>
                          <div class="col-sm-4">
                              {{ user_form.location.errors }}
                          </div>
                      </div>
                      <div class="form-group">
                          <label class="col-sm-2 control-label required" for="id_age_group">{{ user_form.age_group.label_tag }}</label>
                          <div class="col-sm-6">
                              {{ user_form.age_group }}
                          </div>
                          <div class="col-sm-4">
                              {{ user_form.age_group.errors }}
                          </div>
                      </div>
                      <div class="form-group">
                          <label class="col-sm-2 control-label" for="id_gender">{{ user_form.gender.label_tag }}</label>
                          <div class="col-sm-6">
                              {{ user_form.gender }}
                          </div>
                          <div class="col-sm-4">
                              {{ user_form.gender.errors }}
                          </div>
                      </div>
                      <div class="form-group">
                          <label class="col-sm-2 control-label required" for="id_tshirt_size">{{ user_form.tshirt_size.label_tag }}</label>
                          <div class="col-sm-6">
                              {{ user_form.tshirt_size }}
                          </div>
                          <div class="col-sm-4">
                              {{ user_form.tshirt_size.errors }}
                          </div>
                      </div>
                      <div class="form-group">
                          <label class="col-sm-2 control-label required" for="id_occupation">{{ user_form.occupation.label_tag }}</label>
                          <div class="col-sm-6">
                              {{ user_form.occupation }}
                          </div>
                          <div class="col-sm-4">
                              {{ user_form.occupation.errors }}
                          </div>
                      </div>
                      <div class="form-group">
                          <label class="col-sm-2 control-label" for="id_company">{{ user_form.company.label_tag }}</label>
                          <div class="col-sm-6">
                              {{ user_form.company }}
                          </div>
                          <div class="col-sm-4">
                              {{ user_form.company.errors }}
                          </div>
                      </div>
                      <div class="form-group">
                          <label class="col-sm-2 control-label" for="id_company_title">{{ user_form.job_title.label_tag }}</label>
                          <div class="col-sm-6">
                              {{ user_form.job_title }}
                          </div>
                          <div class="col-sm-4">
                              {{ user_form.job_title.errors }}
                          </div>
                      </div>
                      <input name="tshirts[]" type="hidden" id="tshirt-arr-1"/>
                      <input name="tshirts[]" type="hidden" id="tshirt-arr-2"/>
                      {{ ticket_form.ticket }}
                      {{ ticket_form.auxiliary_ticket_id }}
                      <div class="form-group">
                          <div class="col-sm-offset-2 col-sm-6">
                          <button type="submit" class="btn btn-primary">Register!</button>
                          </div>
                      </div>
                  </form>
                  <div class="alert alert-danger hidden" role="alert" id="form-invalid"></div>
                  <div class="alert alert-success" role="alert" id="razorpay-message">
                      You won't be redirected to PyCon Pune Website after payment complete. You will get the payment invoice
                      in your registered email.
                  </div>
              </div>